/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'areas-actuacao': AreasActuacao;
    equipa: Equipa;
    publicacoes: Publicacoe;
    noticias: Noticia;
    parceiros: Parceiro;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'areas-actuacao': AreasActuacaoSelect<false> | AreasActuacaoSelect<true>;
    equipa: EquipaSelect<false> | EquipaSelect<true>;
    publicacoes: PublicacoesSelect<false> | PublicacoesSelect<true>;
    noticias: NoticiasSelect<false> | NoticiasSelect<true>;
    parceiros: ParceirosSelect<false> | ParceirosSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    configuracoes: Configuracoe;
    'sobre-nos': SobreNo;
    impacto: Impacto;
    hero: Hero;
    'chamada-accao': ChamadaAccao;
    faq: Faq;
  };
  globalsSelect: {
    configuracoes: ConfiguracoesSelect<false> | ConfiguracoesSelect<true>;
    'sobre-nos': SobreNosSelect<false> | SobreNosSelect<true>;
    impacto: ImpactoSelect<false> | ImpactoSelect<true>;
    hero: HeroSelect<false> | HeroSelect<true>;
    'chamada-accao': ChamadaAccaoSelect<false> | ChamadaAccaoSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descrição da imagem, importante para acessibilidade (ex: "Mulheres em formação de costura, Beira")
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "areas-actuacao".
 */
export interface AreasActuacao {
  id: number;
  nome: string;
  /**
   * Usado no endereço da página, ex: "educacao-inclusiva"
   */
  slug: string;
  icone?: (number | null) | Media;
  /**
   * Resumo curto, usado na grelha de destaque
   */
  descricaoCurta: string;
  /**
   * Texto completo, usado na página individual da área
   */
  descricaoCompleta?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipa".
 */
export interface Equipa {
  id: number;
  nome: string;
  cargo: string;
  foto?: (number | null) | Media;
  bio?: string | null;
  /**
   * Ordem de exibição na página (menor número aparece primeiro)
   */
  ordem?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publicacoes".
 */
export interface Publicacoe {
  id: number;
  titulo: string;
  descricao?: string | null;
  data: string;
  /**
   * PDF do relatório/publicação
   */
  ficheiro: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias".
 */
export interface Noticia {
  id: number;
  titulo: string;
  /**
   * Usado no endereço da página, ex: "workshop-saude-mental-2026"
   */
  slug: string;
  tipo: 'noticia' | 'evento';
  data: string;
  capa?: (number | null) | Media;
  /**
   * Resumo curto, usado na lista
   */
  resumo: string;
  conteudo?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parceiros".
 */
export interface Parceiro {
  id: number;
  nome: string;
  logotipo: number | Media;
  /**
   * Opcional — site do parceiro
   */
  link?: string | null;
  /**
   * Ordem de exibição (menor número aparece primeiro)
   */
  ordem?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'areas-actuacao';
        value: number | AreasActuacao;
      } | null)
    | ({
        relationTo: 'equipa';
        value: number | Equipa;
      } | null)
    | ({
        relationTo: 'publicacoes';
        value: number | Publicacoe;
      } | null)
    | ({
        relationTo: 'noticias';
        value: number | Noticia;
      } | null)
    | ({
        relationTo: 'parceiros';
        value: number | Parceiro;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "areas-actuacao_select".
 */
export interface AreasActuacaoSelect<T extends boolean = true> {
  nome?: T;
  slug?: T;
  icone?: T;
  descricaoCurta?: T;
  descricaoCompleta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipa_select".
 */
export interface EquipaSelect<T extends boolean = true> {
  nome?: T;
  cargo?: T;
  foto?: T;
  bio?: T;
  ordem?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publicacoes_select".
 */
export interface PublicacoesSelect<T extends boolean = true> {
  titulo?: T;
  descricao?: T;
  data?: T;
  ficheiro?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias_select".
 */
export interface NoticiasSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  tipo?: T;
  data?: T;
  capa?: T;
  resumo?: T;
  conteudo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parceiros_select".
 */
export interface ParceirosSelect<T extends boolean = true> {
  nome?: T;
  logotipo?: T;
  link?: T;
  ordem?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracoes".
 */
export interface Configuracoe {
  id: number;
  nomeOrganizacao: string;
  slogan?: string | null;
  logotipo?: (number | null) | Media;
  endereco?: string | null;
  telefone?: string | null;
  email?: string | null;
  redesSociais?:
    | {
        plataforma: 'facebook' | 'instagram' | 'linkedin' | 'youtube' | 'x' | 'whatsapp' | 'tiktok';
        link: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Liga/desliga secções inteiras do site sem apagar o conteúdo já criado
   */
  paginasActivas?: {
    mostrarEquipa?: boolean | null;
    mostrarImpacto?: boolean | null;
    mostrarPublicacoes?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sobre-nos".
 */
export interface SobreNo {
  id: number;
  capa?: (number | null) | Media;
  quemSomos?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  missao?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  visao?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  valores?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Marcos importantes da organização, em ordem cronológica (ex: fundação, registo oficial, planos estratégicos)
   */
  historia?:
    | {
        /**
         * Ex: "2007", "Março 2015"
         */
        ano: string;
        /**
         * Ex: "Fundação", "Registo oficial"
         */
        titulo: string;
        descricao?: string | null;
        foto?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impacto".
 */
export interface Impacto {
  id: number;
  eyebrow?: string | null;
  titulo?: string | null;
  /**
   * Números de destaque, ex: "1.200+" com descrição "meninas empoderadas em saúde sexual e reprodutiva"
   */
  estatisticas?:
    | {
        icone:
          | 'pessoas'
          | 'saude'
          | 'agricultura'
          | 'protecao'
          | 'educacao'
          | 'comunidade'
          | 'deficiencia'
          | 'genero'
          | 'formacao';
        /**
         * Ex: "1.200+", "15", "3 Províncias"
         */
        numero: string;
        /**
         * Ex: "meninas empoderadas em saúde sexual e reprodutiva"
         */
        descricao: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  modo: 'carrossel' | 'video';
  /**
   * Cada foto pode ter o seu próprio título e frase, tal como no site da Esmabama.
   */
  slidesCarrossel?:
    | {
        imagem: number | Media;
        /**
         * Ex: "Agricultura", "Saúde", "Educação"
         */
        titulo: string;
        /**
         * Frase curta de apoio a esta foto
         */
        texto: string;
        id?: string | null;
      }[]
    | null;
  video?: (number | null) | Media;
  videoTitulo?: string | null;
  videoTexto?: string | null;
  eyebrow?: string | null;
  botaoTexto?: string | null;
  botaoLink?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chamada-accao".
 */
export interface ChamadaAccao {
  id: number;
  titulo: string;
  texto: string;
  botaoTexto: string;
  botaoLink: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  titulo?: string | null;
  perguntas?:
    | {
        pergunta: string;
        resposta: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracoes_select".
 */
export interface ConfiguracoesSelect<T extends boolean = true> {
  nomeOrganizacao?: T;
  slogan?: T;
  logotipo?: T;
  endereco?: T;
  telefone?: T;
  email?: T;
  redesSociais?:
    | T
    | {
        plataforma?: T;
        link?: T;
        id?: T;
      };
  paginasActivas?:
    | T
    | {
        mostrarEquipa?: T;
        mostrarImpacto?: T;
        mostrarPublicacoes?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sobre-nos_select".
 */
export interface SobreNosSelect<T extends boolean = true> {
  capa?: T;
  quemSomos?: T;
  missao?: T;
  visao?: T;
  valores?: T;
  historia?:
    | T
    | {
        ano?: T;
        titulo?: T;
        descricao?: T;
        foto?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impacto_select".
 */
export interface ImpactoSelect<T extends boolean = true> {
  eyebrow?: T;
  titulo?: T;
  estatisticas?:
    | T
    | {
        icone?: T;
        numero?: T;
        descricao?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  modo?: T;
  slidesCarrossel?:
    | T
    | {
        imagem?: T;
        titulo?: T;
        texto?: T;
        id?: T;
      };
  video?: T;
  videoTitulo?: T;
  videoTexto?: T;
  eyebrow?: T;
  botaoTexto?: T;
  botaoLink?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chamada-accao_select".
 */
export interface ChamadaAccaoSelect<T extends boolean = true> {
  titulo?: T;
  texto?: T;
  botaoTexto?: T;
  botaoLink?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  titulo?: T;
  perguntas?:
    | T
    | {
        pergunta?: T;
        resposta?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}